name: Check Secret Value

on:
  workflow_dispatch:  # Permite que o workflow seja acionado manualmente

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:

      - name: SECRET TRUE
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "TRUE" ]; then
            echo "A secret TEST_SECRET é 'TRUE'"
          else
            echo "SKIP"
          fi

      - name: SECRET FALSE
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "FALSE" ]; then
            echo "A secret TEST_SECRET é 'FALSE'"
          else
            echo "SKIP"
          fi
