name: Install Swift

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y clang libicu-dev

    - name: Download Swift
      run: |
        SWIFT_VERSION="5.8.1" # Specify the Swift version
        wget https://swift.org/builds/swift-${SWIFT_VERSION}-release/ubuntu1804/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu18.04.tar.gz
        tar xzf swift-${SWIFT_VERSION}-RELEASE-ubuntu18.04.tar.gz
        sudo mv swift-${SWIFT_VERSION}-RELEASE-ubuntu18.04 /usr/share/swift
        echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH

    - name: Check Swift version
      run: swift --version
