name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requests library
        run: pip install requests pybase64 cryptography

      - name: Update GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SECRET_NAME: 'TEST_SECRET'
          NEW_SECRET_VALUE: 'FALSE'
        run: |
          import requests
          import base64
          import os
          
          new_secret_value = os.environ['NEW_SECRET_VALUE']
          encoded_value = base64.b64encode(new_secret_value.encode()).decode()
          
          url = f"https://api.github.com/repos/{os.environ['REPO']}/actions/secrets/{os.environ['SECRET_NAME']}"
          
          headers = {
              'Authorization': f'token {os.environ["GITHUB_TOKEN"]}',
              'Accept': 'application/vnd.github.v3+json'
          }
          
          response = requests.get(f"https://api.github.com/repos/{os.environ['REPO']}/actions/secrets/public-key", headers=headers)
          public_key_info = response.json()
          key_id = public_key_info['key_id']
          public_key = public_key_info['key']
          
          from cryptography.fernet import Fernet
          import json
          
          fernet = Fernet(public_key.encode())
          encrypted_value = fernet.encrypt(encoded_value.encode())
          
          data = {
              'encrypted_value': encrypted_value.decode(),
              'key_id': key_id
          }
          
          requests.put(url, headers=headers, json=data)
                    
