name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update_secret:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requests library
        run: pip install requests pybase64 cryptography

      - name: Update GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SECRET_NAME: 'TEST_SECRET'
          NEW_SECRET_VALUE: 'FALSE'
        run: |
          python ./.github/workflows/script.py
