name: Pipe 2

on:
  workflow_call:  # Enable this workflow to be called by another
  # Optionally, you can add inputs here
  # inputs:
  #   example_input:
  #     required: true
  #     type: string

jobs:
  job_in_pipe2:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Step
        run: echo "This is Pipe 2 running!"

      - name: Display
        id: display_environment
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "schedule"
          else
            echo "deu ruim"
          fi
