name: Tests

on:
  workflow_call:

jobs:
  tests:
    name: teste
    runs-on:
      labels: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Display
        id: display_environment
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "schedule"
          else
            echo "deu ruim"
