name: E2E Tests

on:
  workflow_call:

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on:
      labels: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Display environment
        id: display_environment
        run: |
          echo "Test"

      - name: Display environment2
        id: display_environment2
        run: |
          echo "${{ github.event_name }}"





# - name: Display
#   id: display_environment
#   run: |
#     if [ "${{ github.event_name }}" == "schedule" ]; then
#       echo "schedule"
#     else
#       echo "deu ruim"
#     fi
