name: Set Repository Variable

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_variable:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: |
          # Clear GITHUB_TOKEN from the environment
          unset GITHUB_TOKEN
          # Authenticate using the provided GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Set Repository Variable
        env:
          NEW_VARIABLE_VALUE: "my_new_value"  # Replace with the value you want to set
        run: |
          gh variable set TEST_SECRET2 --value "$NEW_VARIABLE_VALUE" --repo ${{ github.repository }}
