name: DevOps Troubleshoot Workflow

on:
  workflow_dispatch:

jobs:
  test-maven2:
    runs-on:
      labels: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Set current_date
        run: |
          current_date=$(date +'%B %Y')
          echo "MONTH_YEAR=$MONTH_YEAR"

          closest_future_version=$(jq -r --arg today "$current_date" '
          map(select((.description == "Planned Deployments") and (.startDate >= $today)))
          | sort_by(.startDate)')

          echo "Closest future fixVersion is: $closest_future_version"
  
