name: Manual Swift Setup CI

on:
  push:
    branches:
      - main  # Change this to your desired branch
  pull_request:
    branches:
      - main  # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use your on-premise runner label if necessary

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libicu-dev

    - name: Download and Install Swift
      run: |
        SWIFT_VERSION="5.7"  # Change this to your desired Swift version
        SWIFT_URL="https://swift.org/builds/swift-$SWIFT_VERSION-RELEASE/ubuntu2004/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu20.04.tar.gz"
        
        # Check if the URL is valid
        if curl --output /dev/null --silent --head --fail "$SWIFT_URL"; then
          echo "Downloading Swift $SWIFT_VERSION from $SWIFT_URL"
          curl -s "$SWIFT_URL" | tar xz -C /usr/share --strip-components=1
          echo "/usr/share/swift/usr/bin" >> $GITHUB_PATH
        else
          echo "Error: Swift version $SWIFT_VERSION not available."
          exit 1
        fi

    - name: Verify Swift Installation
      run: swift --version

    - name: Build and Test
      run: |
        swift build
        swift test
