name: DevOps Troubleshoot Workflow

on:
  workflow_dispatch:

jobs:
  export_custom_value:
    runs-on: ubuntu-latest
    outputs:
      run_id: ${{ steps.set_output.outputs.run_id }}
    steps:
      - name: Set Custom Output
        id: set_output
        run: |
          echo "run_id=${GITHUB_RUN_ID}" >> $GITHUB_OUTPUT

  use_custom_value:
    runs-on: ubuntu-latest
    needs: export_custom_value
    steps:
      - name: Use the Custom Output
        run: |
          echo "The exported GITHUB_RUN_ID is: ${{ needs.export_custom_value.outputs.run_id }}"


      
      # - name: Set current_date
      #   run: |
      #     current_date=$(date +'%B %Y')
      #     echo "MONTH_YEAR=$current_date"

      #     closest_future_version=$(jq -r --arg today "$current_date" '
      #     map(select((.description == "Planned Deployments") and (.startDate >= $today)))')

      #     echo "Closest future fixVersion is: $closest_future_version"
  
