name: DevOps Troubleshoot Workflow

on:
  workflow_dispatch:

jobs:
  test-maven2:
    runs-on:
      labels: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Set current_date
        run: |
          current_date=$(date +'%m%Y')
          echo "CURRENT_DATE=$current_date"
  
