name: Manual Swift Setup CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use your on-premise runner label if necessary

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
        
    - name: Get swift version
      run: swift --version 
