name: DevOps Troubleshoot Workflow

on:
  workflow_dispatch:

jobs:
  export_run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Export GITHUB_RUN_ID
        run: echo "RUN_ID=${GITHUB_RUN_ID}" >> $GITHUB_ENV

  use_run_id:
    runs-on: ubuntu-latest
    needs: export_run_id  # This job depends on the previous job
    steps:
      - name: Use the exported GITHUB_RUN_ID
        run: echo "The exported GITHUB_RUN_ID is: $RUN_ID"


      
      # - name: Set current_date
      #   run: |
      #     current_date=$(date +'%B %Y')
      #     echo "MONTH_YEAR=$current_date"

      #     closest_future_version=$(jq -r --arg today "$current_date" '
      #     map(select((.description == "Planned Deployments") and (.startDate >= $today)))')

      #     echo "Closest future fixVersion is: $closest_future_version"
  
