name: Manual Swift Setup CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # Use your on-premise runner label if necessary

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10.1"
        
    - name: Printar IP do Runner
      run: |
        echo "IP público do runner:"
        curl ifconfig.me  # Para obter o IP público
        echo "IP local do runner:"
        hostname -I     # Para obter o IP local
