name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests

    defaults:
      run:
        shell: bash

    steps:
      - name: Display
        id: display_environment
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "schedule"
          else
            echo "deu ruim"
