name: Update Secret

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  update_secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Retrieve public key
        id: get_public_key
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TEST_SECRET }}
        run: |
          response=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          
          echo "public_key=$(echo $response | jq -r .key)" >> $GITHUB_ENV
          echo "key_id=$(echo $response | jq -r .key_id)" >> $GITHUB_ENV

      - name: Update GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TEST_SECRET }}
          SECRET_NAME: "TEST_SECRET" # Replace with your secret name
          NEW_SECRET_VALUE: "FALSE" # Replace with the new secret value
        run: |
          # Base64 encode the new secret value
          ENCODED_VALUE=$(echo -n "${NEW_SECRET_VALUE}" | openssl rsautl -encrypt -pubin -inkey <(echo "${public_key}" | base64 --decode) | base64 | tr -d '\n')
          
          # Update the secret using GitHub API
          curl -X PUT \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/${SECRET_NAME} \
            -d "{\"encrypted_value\":\"${ENCODED_VALUE}\", \"key_id\":\"${key_id}\"}"
