name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Public Key
        id: get_public_key
        run: |
          response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "::set-output name=public_key::$(echo $response | jq -r .key)"
          echo "::set-output name=key_id::$(echo $response | jq -r .key_id)"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install requests pybase64 cryptography pycryptodome   


      - name: Update GitHub Secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: 'update_secrets'
          REPO: ${{ github.repository }}  # Nome do repositório no formato "owner/repo"
          SECRET_NAME: 'TEST_SECRET'  # Nome do segredo que você deseja atualizar
          NEW_SECRET_VALUE: 'FALSE'  # Novo valor do segredo
          KEY_ID: ${{ steps.get_public_key.outputs.key_id }}
          PUBLIC_KEY: ${{ steps.get_public_key.outputs.public_key }}
        run: python ./.github/workflows/script3.py

      - name: Verificar valor da secret
        run: |
          if [ "${{ secrets.TEST_SECRET }}" == "TRUE" ]; then
            echo "A secret TEST_SECRET é verdadeira."
          elif [ "${{ secrets.TEST_SECRET }}" == "FALSE" ]; then
            echo "A secret TEST_SECRET é falsa."
          else
            echo "A secret TEST_SECRET não é um valor esperado."
            exit 1
          fi
