name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Get Public Key
        id: get_public_key
        run: |
          response=$(curl -H "Authorization: token ${{ secrets.PAT_TEST_SECRET }}" \
                           -H "Accept: application/vnd.github.v3+json" \
                           https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "::set-output name=public_key::$(echo $response | jq -r .key)"
          echo "::set-output name=key_id::$(echo $response | jq -r .key_id)"

      - name: Encrypt Secret
        id: encrypt_secret
        uses: ./github/actions/encrypt-secret
        with:
          secret_value: 'SEU_VALOR_DE_SEGREDO'  # Substitua pelo valor que deseja criptografar
          public_key: ${{ steps.get_public_key.outputs.public_key }}
          key_id: ${{ steps.get_public_key.outputs.key_id }}

      # - name: Update Secret
      #   run: |
      #     curl -X PUT -H "Authorization: token ${{ secrets.PAT_TEST_SECRET }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/actions/secrets/NOME_DO_SECRETO -d '{"encrypted_value": "${{ steps.encrypt_secret.outputs.encrypted_value }}", "key_id": "${{ steps.get_public_key.outputs.key_id }}"}'
