name: Update Secret Github CLI

on:
  workflow_dispatch:  # Permite que o workflow seja acionado manualmente

jobs:
  update-secret:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        run: |
          gh auth login --with-token <<< ${{ secrets.TEST_SECRET }}

      - name: Update GitHub Secret
        env:
          REPO: ${{ github.repository }}
          NEW_SECRET_VALUE: "FALSE"
        run: |
          gh variable set TEST_SECRET2 --body "$NEW_SECRET_VALUE" --repo "$REPO"

      - name: Test GitHub Secret
        run: |
          VARIABLE_VALUE=$(gh variable get TEST_SECRET2 --repo ${{ github.repository }})
          echo "The value of MY_VAR is: $VARIABLE_VALUE"

      - name: Validate variable
        run: |
          if [ ${{vars.TEST_SECRET2}} == "false" || ${{vars.TEST_SECRET2}} == "FALSE" ]; then
            echo "false FALSE"
            exit 1
          else
            echo "passou"
          fi

      - name: Validate ok
        run: |
          echo "ok"
